### ISSUE TITLE
not crate accompaniment ?

### ISSUE THREAD

**Issue by badboy-tian** [mohammadmansour200/lite-spleeter#4]
hi. use lite-separate -i xxx.mp3 -o ./  
but only vocals.mp3, no accompaniment.mp3?

**Comment by mohammadmansour200** [comment]
Unfortunately, I have made it limited to vocals only

**Comment by badboy-tian** [comment]
Can you add a switch function? For example-makeAll

Mohammad Abdul-Tawab ***@***.***>于2024年12月13日 周五21:17写道：

**Comment by badboy-tian** [comment]
@mohammadmansour200 i finish it  

https://github.com/mohammadmansour200/lite-spleeter/pull/5

```
lite-spleeter separate audio_example.mp3  -o audio_output_path
lite-spleeter separate audio_example.mp3  -o audio_output_path --all
```

**Comment by mohammadmansour200** [comment]
Thanks very much, unfortunately I am not planning to add accompaniment support.
